"""initial schema

Revision ID: fee632b62115
Revises:
Create Date: 2026-08-02 15:30:45.332741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee632b62115'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AuditLogs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'AuditLogs', ['action'], unique=False)
    op.create_index('idx_audit_actor', 'AuditLogs', ['actor_id'], unique=False)
    op.create_index('idx_audit_created', 'AuditLogs', ['created_at'], unique=False)
    op.create_index('idx_audit_resource', 'AuditLogs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('Brands',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brand_active', 'Brands', ['is_active'], unique=False)
    op.create_index('idx_brand_slug', 'Brands', ['slug'], unique=False)
    op.create_index(op.f('ix_Brands_is_active'), 'Brands', ['is_active'], unique=False)
    op.create_index(op.f('ix_Brands_slug'), 'Brands', ['slug'], unique=True)
    op.create_table('Categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('depth_level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['Categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_active', 'Categories', ['is_active'], unique=False)
    op.create_index('idx_category_parent', 'Categories', ['parent_id'], unique=False)
    op.create_index('idx_category_slug', 'Categories', ['slug'], unique=False)
    op.create_index(op.f('ix_Categories_is_active'), 'Categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_Categories_slug'), 'Categories', ['slug'], unique=True)
    op.create_table('ConversationSessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('final_psych_state', sa.String(length=50), nullable=True),
    sa.Column('final_consult_strategy', sa.Text(), nullable=True),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('iteration_count', sa.Integer(), nullable=False),
    sa.Column('conversion_outcome', sa.String(length=50), nullable=False),
    sa.Column('linked_order_id', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    # linked_order_id -> Orders.id KHÔNG khai báo inline ở đây — Orders và ConversationSessions
    # tham chiếu vòng tròn lẫn nhau (Orders.conversation_session_id -> ConversationSessions.id).
    # Constraint này được thêm sau bằng op.create_foreign_key() ngay sau khi bảng Orders được
    # tạo, tránh lỗi "Failed to open the referenced table" do MySQL yêu cầu bảng đích phải tồn
    # tại sẵn khi tạo FK inline trong CREATE TABLE.
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_active', 'ConversationSessions', ['last_active_at'], unique=False)
    op.create_index('idx_session_channel', 'ConversationSessions', ['channel'], unique=False)
    op.create_index('idx_session_outcome', 'ConversationSessions', ['conversion_outcome'], unique=False)
    op.create_index('idx_session_status', 'ConversationSessions', ['status'], unique=False)
    op.create_index('idx_session_thread', 'ConversationSessions', ['thread_id'], unique=False)
    op.create_index('idx_session_user', 'ConversationSessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_ConversationSessions_channel'), 'ConversationSessions', ['channel'], unique=False)
    op.create_index(op.f('ix_ConversationSessions_conversion_outcome'), 'ConversationSessions', ['conversion_outcome'], unique=False)
    op.create_index(op.f('ix_ConversationSessions_last_active_at'), 'ConversationSessions', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_ConversationSessions_status'), 'ConversationSessions', ['status'], unique=False)
    op.create_index(op.f('ix_ConversationSessions_thread_id'), 'ConversationSessions', ['thread_id'], unique=True)
    op.create_table('Orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_code', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('shipping_address_id', sa.BigInteger(), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('discount_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('shipping_fee', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('shipping_method', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('staff_notes', sa.Text(), nullable=True),
    sa.Column('conversation_session_id', sa.BigInteger(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_session_id'], ['ConversationSessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['UserAddresses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_code', 'Orders', ['order_code'], unique=False)
    op.create_index('idx_order_created', 'Orders', ['created_at'], unique=False)
    op.create_index('idx_order_payment', 'Orders', ['payment_status'], unique=False)
    op.create_index('idx_order_session', 'Orders', ['conversation_session_id'], unique=False)
    op.create_index('idx_order_status', 'Orders', ['status'], unique=False)
    op.create_index('idx_order_user', 'Orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_Orders_conversation_session_id'), 'Orders', ['conversation_session_id'], unique=False)
    op.create_index(op.f('ix_Orders_order_code'), 'Orders', ['order_code'], unique=True)
    op.create_index(op.f('ix_Orders_payment_status'), 'Orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_Orders_status'), 'Orders', ['status'], unique=False)
    # Vế còn lại của FK vòng tròn — Orders đã tồn tại nên add constraint này an toàn ngay bây giờ.
    op.create_foreign_key(
        'fk_conversationsessions_linked_order_id_orders',
        'ConversationSessions', 'Orders',
        ['linked_order_id'], ['id'],
        ondelete='SET NULL',
    )
    op.create_table('Tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('tag_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_tag_type', 'Tags', ['tag_type'], unique=False)
    op.create_index(op.f('ix_Tags_tag_type'), 'Tags', ['tag_type'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=True),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('idx_user_active', 'Users', ['is_active'], unique=False)
    op.create_index('idx_user_email', 'Users', ['email'], unique=False)
    op.create_index('idx_user_phone', 'Users', ['phone'], unique=False)
    op.create_index('idx_user_role', 'Users', ['role'], unique=False)
    op.create_index(op.f('ix_Users_is_active'), 'Users', ['is_active'], unique=False)
    op.create_table('APIKeys',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['Users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_apikey_active', 'APIKeys', ['is_active'], unique=False)
    op.create_index('idx_apikey_hash', 'APIKeys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_APIKeys_is_active'), 'APIKeys', ['is_active'], unique=False)
    op.create_index(op.f('ix_APIKeys_key_hash'), 'APIKeys', ['key_hash'], unique=True)
    op.create_table('AgentPerformanceLogs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('retrieval_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('retrieved_product_ids', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ConversationSessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_perf_agent', 'AgentPerformanceLogs', ['agent_name'], unique=False)
    op.create_index('idx_perf_latency', 'AgentPerformanceLogs', ['latency_ms'], unique=False)
    op.create_index('idx_perf_session', 'AgentPerformanceLogs', ['session_id'], unique=False)
    op.create_table('Carts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('session_key', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cart_expires', 'Carts', ['expires_at'], unique=False)
    op.create_index('idx_cart_session', 'Carts', ['session_key'], unique=False)
    op.create_index('idx_cart_user', 'Carts', ['user_id'], unique=False)
    op.create_index(op.f('ix_Carts_expires_at'), 'Carts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_Carts_session_key'), 'Carts', ['session_key'], unique=False)
    op.create_table('ConversationMessages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ConversationSessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_msg_agent', 'ConversationMessages', ['agent_name'], unique=False)
    op.create_index('idx_msg_session', 'ConversationMessages', ['session_id'], unique=False)
    op.create_index('idx_msg_turn', 'ConversationMessages', ['session_id', 'turn_number'], unique=False)
    op.create_table('Payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('gateway_response', sa.JSON(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_order', 'Payments', ['order_id'], unique=False)
    op.create_index('idx_payment_status', 'Payments', ['status'], unique=False)
    op.create_index('idx_payment_transaction', 'Payments', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_Payments_status'), 'Payments', ['status'], unique=False)
    op.create_index(op.f('ix_Payments_transaction_id'), 'Payments', ['transaction_id'], unique=False)
    op.create_table('Products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('brand_id', sa.BigInteger(), nullable=True),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('sale_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('embedding_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['Brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_product_brand', 'Products', ['brand_id'], unique=False)
    op.create_index('idx_product_category', 'Products', ['category_id'], unique=False)
    op.create_index('idx_product_embedding', 'Products', ['embedding_status'], unique=False)
    op.create_index('idx_product_id', 'Products', ['id'], unique=False)
    op.create_index('idx_product_price', 'Products', ['unit_price'], unique=False)
    op.create_index('idx_product_status', 'Products', ['status'], unique=False)
    op.create_index('idx_product_stock', 'Products', ['in_stock', 'stock_qty'], unique=False)
    op.create_index(op.f('ix_Products_in_stock'), 'Products', ['in_stock'], unique=False)
    op.create_table('PsychStateLogs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('psych_state', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.DECIMAL(precision=4, scale=3), nullable=False),
    sa.Column('primary_concern', sa.String(length=255), nullable=True),
    sa.Column('consult_strategy', sa.String(length=500), nullable=True),
    sa.Column('raw_output', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ConversationSessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_psych_session', 'PsychStateLogs', ['session_id'], unique=False)
    op.create_index('idx_psych_state', 'PsychStateLogs', ['psych_state'], unique=False)
    op.create_table('SystemConfigs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=255), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['Users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_index('idx_config_key', 'SystemConfigs', ['config_key'], unique=False)
    op.create_table('UserAddresses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_address_default', 'UserAddresses', ['user_id', 'is_default'], unique=False)
    op.create_index('idx_address_user', 'UserAddresses', ['user_id'], unique=False)
    op.create_table('UserProfiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('zodiac_sign', sa.String(length=50), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('loyalty_points', sa.Integer(), nullable=False),
    sa.Column('customer_segment', sa.String(length=50), nullable=True),
    sa.Column('staff_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_profile_segment', 'UserProfiles', ['customer_segment'], unique=False)
    op.create_index('idx_profile_zodiac', 'UserProfiles', ['zodiac_sign'], unique=False)
    op.create_index(op.f('ix_UserProfiles_customer_segment'), 'UserProfiles', ['customer_segment'], unique=False)
    op.create_index(op.f('ix_UserProfiles_zodiac_sign'), 'UserProfiles', ['zodiac_sign'], unique=False)
    op.create_table('CartItems',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['Carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['Products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', name='uq_cart_product')
    )
    op.create_index('idx_cartitem_cart', 'CartItems', ['cart_id'], unique=False)
    op.create_table('OrderItems',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['Products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_order', 'OrderItems', ['order_id'], unique=False)
    op.create_index('idx_item_product', 'OrderItems', ['product_id'], unique=False)
    op.create_table('ProductImages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['Products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_image_primary', 'ProductImages', ['product_id', 'is_primary'], unique=False)
    op.create_index('idx_image_product', 'ProductImages', ['product_id'], unique=False)
    op.create_table('ProductTags',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['Products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['Tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'tag_id')
    )
    op.create_table('ProductReviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('order_item_id', sa.BigInteger(), nullable=True),
    sa.Column('rating', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(), nullable=True),
    sa.Column('embedding_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['OrderItems.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['Products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_embedding', 'ProductReviews', ['embedding_status'], unique=False)
    op.create_index('idx_review_product', 'ProductReviews', ['product_id'], unique=False)
    op.create_index('idx_review_published', 'ProductReviews', ['is_published'], unique=False)
    op.create_index('idx_review_user', 'ProductReviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_ProductReviews_embedding_status'), 'ProductReviews', ['embedding_status'], unique=False)
    op.create_index(op.f('ix_ProductReviews_is_published'), 'ProductReviews', ['is_published'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ProductReviews_is_published'), table_name='ProductReviews')
    op.drop_index(op.f('ix_ProductReviews_embedding_status'), table_name='ProductReviews')
    op.drop_index('idx_review_user', table_name='ProductReviews')
    op.drop_index('idx_review_published', table_name='ProductReviews')
    op.drop_index('idx_review_product', table_name='ProductReviews')
    op.drop_index('idx_review_embedding', table_name='ProductReviews')
    op.drop_table('ProductReviews')
    op.drop_table('ProductTags')
    op.drop_index('idx_image_product', table_name='ProductImages')
    op.drop_index('idx_image_primary', table_name='ProductImages')
    op.drop_table('ProductImages')
    op.drop_index('idx_item_product', table_name='OrderItems')
    op.drop_index('idx_item_order', table_name='OrderItems')
    op.drop_table('OrderItems')
    op.drop_index('idx_cartitem_cart', table_name='CartItems')
    op.drop_table('CartItems')
    op.drop_index(op.f('ix_UserProfiles_zodiac_sign'), table_name='UserProfiles')
    op.drop_index(op.f('ix_UserProfiles_customer_segment'), table_name='UserProfiles')
    op.drop_index('idx_profile_zodiac', table_name='UserProfiles')
    op.drop_index('idx_profile_segment', table_name='UserProfiles')
    op.drop_table('UserProfiles')
    op.drop_index('idx_address_user', table_name='UserAddresses')
    op.drop_index('idx_address_default', table_name='UserAddresses')
    op.drop_table('UserAddresses')
    op.drop_index('idx_config_key', table_name='SystemConfigs')
    op.drop_table('SystemConfigs')
    op.drop_index('idx_psych_state', table_name='PsychStateLogs')
    op.drop_index('idx_psych_session', table_name='PsychStateLogs')
    op.drop_table('PsychStateLogs')
    op.drop_index(op.f('ix_Products_in_stock'), table_name='Products')
    op.drop_index('idx_product_stock', table_name='Products')
    op.drop_index('idx_product_status', table_name='Products')
    op.drop_index('idx_product_price', table_name='Products')
    op.drop_index('idx_product_id', table_name='Products')
    op.drop_index('idx_product_embedding', table_name='Products')
    op.drop_index('idx_product_category', table_name='Products')
    op.drop_index('idx_product_brand', table_name='Products')
    op.drop_table('Products')
    op.drop_index(op.f('ix_Payments_transaction_id'), table_name='Payments')
    op.drop_index(op.f('ix_Payments_status'), table_name='Payments')
    op.drop_index('idx_payment_transaction', table_name='Payments')
    op.drop_index('idx_payment_status', table_name='Payments')
    op.drop_index('idx_payment_order', table_name='Payments')
    op.drop_table('Payments')
    op.drop_index('idx_msg_turn', table_name='ConversationMessages')
    op.drop_index('idx_msg_session', table_name='ConversationMessages')
    op.drop_index('idx_msg_agent', table_name='ConversationMessages')
    op.drop_table('ConversationMessages')
    op.drop_index(op.f('ix_Carts_session_key'), table_name='Carts')
    op.drop_index(op.f('ix_Carts_expires_at'), table_name='Carts')
    op.drop_index('idx_cart_user', table_name='Carts')
    op.drop_index('idx_cart_session', table_name='Carts')
    op.drop_index('idx_cart_expires', table_name='Carts')
    op.drop_table('Carts')
    op.drop_index('idx_perf_session', table_name='AgentPerformanceLogs')
    op.drop_index('idx_perf_latency', table_name='AgentPerformanceLogs')
    op.drop_index('idx_perf_agent', table_name='AgentPerformanceLogs')
    op.drop_table('AgentPerformanceLogs')
    op.drop_index(op.f('ix_APIKeys_key_hash'), table_name='APIKeys')
    op.drop_index(op.f('ix_APIKeys_is_active'), table_name='APIKeys')
    op.drop_index('idx_apikey_hash', table_name='APIKeys')
    op.drop_index('idx_apikey_active', table_name='APIKeys')
    op.drop_table('APIKeys')
    op.drop_index(op.f('ix_Users_is_active'), table_name='Users')
    op.drop_index('idx_user_role', table_name='Users')
    op.drop_index('idx_user_phone', table_name='Users')
    op.drop_index('idx_user_email', table_name='Users')
    op.drop_index('idx_user_active', table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Tags_tag_type'), table_name='Tags')
    op.drop_index('idx_tag_type', table_name='Tags')
    op.drop_table('Tags')
    # Vế vòng tròn phải drop TRƯỚC khi drop bảng Orders — constraint này tham chiếu tới Orders,
    # MySQL từ chối DROP TABLE Orders nếu ConversationSessions còn FK trỏ vào nó.
    op.drop_constraint('fk_conversationsessions_linked_order_id_orders', 'ConversationSessions', type_='foreignkey')
    op.drop_index(op.f('ix_Orders_status'), table_name='Orders')
    op.drop_index(op.f('ix_Orders_payment_status'), table_name='Orders')
    op.drop_index(op.f('ix_Orders_order_code'), table_name='Orders')
    op.drop_index(op.f('ix_Orders_conversation_session_id'), table_name='Orders')
    op.drop_index('idx_order_user', table_name='Orders')
    op.drop_index('idx_order_status', table_name='Orders')
    op.drop_index('idx_order_session', table_name='Orders')
    op.drop_index('idx_order_payment', table_name='Orders')
    op.drop_index('idx_order_created', table_name='Orders')
    op.drop_index('idx_order_code', table_name='Orders')
    op.drop_table('Orders')
    op.drop_index(op.f('ix_ConversationSessions_thread_id'), table_name='ConversationSessions')
    op.drop_index(op.f('ix_ConversationSessions_status'), table_name='ConversationSessions')
    op.drop_index(op.f('ix_ConversationSessions_last_active_at'), table_name='ConversationSessions')
    op.drop_index(op.f('ix_ConversationSessions_conversion_outcome'), table_name='ConversationSessions')
    op.drop_index(op.f('ix_ConversationSessions_channel'), table_name='ConversationSessions')
    op.drop_index('idx_session_user', table_name='ConversationSessions')
    op.drop_index('idx_session_thread', table_name='ConversationSessions')
    op.drop_index('idx_session_status', table_name='ConversationSessions')
    op.drop_index('idx_session_outcome', table_name='ConversationSessions')
    op.drop_index('idx_session_channel', table_name='ConversationSessions')
    op.drop_index('idx_session_active', table_name='ConversationSessions')
    op.drop_table('ConversationSessions')
    op.drop_index(op.f('ix_Categories_slug'), table_name='Categories')
    op.drop_index(op.f('ix_Categories_is_active'), table_name='Categories')
    op.drop_index('idx_category_slug', table_name='Categories')
    op.drop_index('idx_category_parent', table_name='Categories')
    op.drop_index('idx_category_active', table_name='Categories')
    op.drop_table('Categories')
    op.drop_index(op.f('ix_Brands_slug'), table_name='Brands')
    op.drop_index(op.f('ix_Brands_is_active'), table_name='Brands')
    op.drop_index('idx_brand_slug', table_name='Brands')
    op.drop_index('idx_brand_active', table_name='Brands')
    op.drop_table('Brands')
    op.drop_index('idx_audit_resource', table_name='AuditLogs')
    op.drop_index('idx_audit_created', table_name='AuditLogs')
    op.drop_index('idx_audit_actor', table_name='AuditLogs')
    op.drop_index('idx_audit_action', table_name='AuditLogs')
    op.drop_table('AuditLogs')
    # ### end Alembic commands ###
